apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      containers:
      - name: alert-manager
        image: chiluka123/alert-manager:stable-v0.2
        ports:
        - containerPort: 5001
        env:
        - name: SLACK_WEBHOOK_URL
          value: "SLACK_WEBHOOK_URL"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
